---
title: "Krieger und Gott"
author: "André-Pascal Werthwein"
date: "21 Januar 2019"
output: pdf_document
---

# Von Listigkeit und Stärke

Es begab sich zu einer Zeit, die schon lange in Vergessenheit geraten ist, an einem Ort, an dessen Schöpfung wir beteiligt waren, den wir aber selbst nie gesehen haben. Es geschah an einem Ort, der fernab unseres sehenden Auges lag, und dennoch nah genug war, sodass wir ihn zu dieser Zeit gewiss hätten spüren können. Es geschah im Reich der Asen; in Asgard. Heute dringt nur noch wenig von diesem Ort zu uns vor. So mancher Mythos und so manche Sage treibt an der Oberfläche unseres Bewusstseins, kommt immer wieder über uns und beschäftigt uns. Verwaschen von Zeit, mehr Lüge als Wahrheit, durchdringen uns diese Legenden doch, fesseln unseren Geist mit Inspiration und Faszination. Nun, zu eben dieser Zeit begab es sich also. Es ist das Abenteuer zweier Männer, nun ja nicht ganz Männer. Sie waren etwas anderes, etwas -- mehr.

Es waren keine geringeren als Thor und Loki, die sich in eine erlebnisreiche Geschichte verstrickten. Eine Geschichte, in der sie alle -- wie auch wir -- einen neuen Blick für die Geschehnisse entwickeln sollten. Nicht die Geschehnisse im Himmelsreich der Götter, nein, sondern die Geschehnisse, die um uns herum passieren, uns prägen und die vor allem unser Bild Anderer bestimmen.

All das beginnt mit einem Diebstahl. Jedoch aber nicht irgendein Diebstahl. Kein Silber, kein Gold und auch keine Juwelen. Nein, es war nichts Geringeres, als Mjölnir selbst, Thors sagenumwobener Hammer. Man hatte dem Gott und Krieger seine Waffe genommen. Eine Waffe, die gepaart mit Thors unerschöpflicher Kraft, so manchen Feind abgewehrt und so manchem Angriff in einen Sieg verwandelt hatte.

Kurz um, ein Gegenstand, ohne den sich Thor fühlte, als habe man ihm seinen Arm genommen. Doch nicht nur, dass der Gott sich ohne seinen Hammer, unvollständig und verwundbar fühlte, Mjölnir stellte nun auch eine Gefahr für sich und sein Geschlecht dar.

_Wer aber hatte sich dieses Verbrechens schuldig gemacht? Wer hatte sich dieser Waffe ermächtigt?_ Die Antworten auf all diese Fragen ließen nicht lange auf sich warten.

Es war ein Jötunn, ein Feind der Asen, war gewesen. Thrymr. Sein Ziel war jedoch nicht der schlichte Besitz von Mjölnir. Der Hammer selbst war vielmehr das Mittel zum Zweck und der Zweck war Freyja. Denn Thrymr verlangte die schöne Wanengöttin -- Trägern von Brisingamen -- zur Frau. Doch die Wanengöttin war nicht bereit sich dieser Erpressung hinzugeben.

So mussten Thor und sein Gefährte Loki zu anderen Mitteln greifen. Kurzerhand steckte Loki den stolzen Krieger unerschöpflicher Kraft in das Kleid eines Weibes. Thor war es nun, der Thrymr heiraten würde. So geschah es. Beinahe hätte Sie jedoch die ungestüme Natur Thors verraten. Lokis Trickreichtum rettete sie jedoch. Thor war es abermals vergönnt seinen Hammer zu schwingen, denn in genau dem Moment, da Thor Mjölnir in den Händen hielt, kam der Tod über den getäuschten Thrymr.

So war es am Ende nicht die unerschöpfliche Kraft und der eisenharte Geist eines Kriegers, der zum Sieg verhalf, sondern windige und listige Geist Lokis.